all:
	gcc concurrency4.c -o concurrency4 -lpthread -Wall
	gcc concurrency4part1.c -o concurrency4part1 -lpthread -Wall
	gcc smoker.c -o smoker -lpthread -Wall
clean:
	rm concurrency4
	rm smoker
	rm concurrency4part1
