all:
	gcc concurrency4.c -o concurrency4 -lpthread -Wall
	gcc concurrency4part1.c -o concurrency4part1 -lpthread -Wall
	gcc chainsmoker.c -o chainsmoker -lpthread - Wall
clean:
	rm concurrency4
	rm chainsmoker
	rm concurrency4part1
